# -*- coding: utf-8 -*-
"""DSA4213 Collaborative Filtering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IRZlTngD7KWedryeXWBW4ZH4m_iomBDV
"""

import pandas as pd
import numpy as np
from zipfile import ZipFile
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from pathlib import Path
import matplotlib.pyplot as plt
from sklearn.neighbors import NearestNeighbors


movies = pd.read_csv("movies_full.csv")
df = pd.read_csv("ratings.csv", index_col = 0)


movies = movies[['movieId', 'title', 'year_of_release','genres', 'extract']]
movies.rename(columns={'extract': 'Explanation', 'year_of_release':'Release Year'}, inplace = True)
movies = movies.dropna()
movies['Source'] = 'collaborative filtering'


pivot_df = df.pivot_table(index='movieId', columns='userId', values='rating')
pivot_df = pivot_df.fillna(0)


# Drop columns with all zeros (movies not rated by any user)
pivot_df_filtered = pivot_df.loc[:, (pivot_df != 0).any(axis=0)]

# Instantiate NearestNeighbors with cosine similarity
knn = NearestNeighbors(metric='cosine', algorithm='brute')

# Fit the model
knn.fit(pivot_df_filtered)

def movie_recommender(movie_title, k=10):
    # Find the movieId of the input movie title
    movie_id = movies[movies['title'].str.contains(movie_title, case=False)]['movieId'].values[0]

    # Find the k-nearest neighbors of the input movie
    distances, indices = knn.kneighbors(pivot_df_filtered.loc[movie_id].values.reshape(1, -1), n_neighbors=k+1)

    # Get the movieIds of the k-nearest neighbors
    neighbor_movie_ids = pivot_df_filtered.iloc[indices[0][1:]].index.tolist()

    # Get the movie titles and genres from the movies DataFrame
    neighbor_movies_info = movies[movies['movieId'].isin(neighbor_movie_ids)][['title', 'Release Year', 'genres','Source', 'Explanation']]

    neighbor_movies_df = pd.DataFrame(neighbor_movies_info)

    return neighbor_movies_df

# Example usage
input_movie_title = "Toy Story"
recommended_movies = movie_recommender(input_movie_title)
print(recommended_movies)
